name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: source $GITHUB_WORKSPACE/PKGBUILD && pacman -Syu --noconfirm --needed "${makedepends[@]}" "${depends[@]}" base-devel
    - name: Create build user
      run: useradd -m build
    - name: Give permission for build directory
      run: chown build $GITHUB_WORKSPACE
    - name: Build package
      run: su build -c "cd $GITHUB_WORKSPACE && makepkg"
