name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux

    steps:
    - uses: actions/checkout@v2
    - name: Upgrade arch
      run: pacman -Syu --noconfirm
    - name: Install base-devel
      run: pacman -S --noconfirm base-devel
    - name: Create build user
      run: useradd -m build
    - name: Build package
      run: su build -c makepkg
